server:
  port: 9101
spring:
  application:
    name: nacos-consumer
  cloud:
    discovery:
      server-addr: 121.248.201.29:8848
    sentinel:
      transport:
        # 配置sentinel dashboard地址
        dashboard: localhost:8080
        # 默认是8719端口 被占用的话会自动+1 直到找到未被占用的端口
        port: 8719

service-url:
  nacos-user-service: http://nacos-provider